services:
  api:
    build: .

    ports:
      - "8000:8000"

    environment:
      CHROMA_PATH: /app/chroma_db
      OLLAMA_HOST: http://host.docker.internal:11434

    volumes:
      - ./chroma_db:/app/chroma_db
      - ./data:/app/data

    extra_hosts:
      - "host.docker.internal:host-gateway"
